version: '3.8'

services:
  app:
    container_name: ojs3_staging
    build:
      context: ..
      dockerfile: adi/Dockerfile
    ports:
      - "8448:80"  # Different port for staging
    volumes:
      - ../:/var/www/html
      - ojs_files:/var/www/html/files
    depends_on: []

volumes:
  ojs_files: 